### ISSUE TITLE
Pixelation at the bottom / top

### ISSUE THREAD

**Issue by yych42** [nikstar/VariableBlur#1]
https://github.com/aheze/VariableBlurView/issues/2

A suggested fix is to set a higher scale:

`backdropLayer?.setValue(15, forKey: "scale")`

Maybe this could be a param?

**Comment by nikstar** [comment]
Thanks @yych42! It looks much better now.

I've set it to `window.screen.scale` (usually 3.0). I don't see any reason to set it higher but let me know if you disagree.

https://github.com/nikstar/VariableBlur/blob/7b64063ae423035083b89ddfa2981832fc935d03/Sources/VariableBlur/VariableBlur.swift#L70-L75

**Comment by yych42** [comment]
Wow that was fast. Thanks!
