### ISSUE TITLE
Can't change UIBlurEffectMaterial

### ISSUE THREAD

**Issue by esmondmissen** [nikstar/VariableBlur#2]
I can't seem to change the blur material to .systemMaterialDark, or anything else. I've tried modifying this line here:

`super.init(effect: UIBlurEffect(style: .systemMaterialDark))`

Not sure if this is outside the scope of this project

**Comment by nikstar** [comment]
Hi @esmondmissen. I think I turn off a layer relevant to this in line 62. You can try experimenting with that. 
https://github.com/nikstar/VariableBlur/blob/main/Sources/VariableBlur/VariableBlur.swift#L60-L63
